# Generated by Django 5.1.2 on 2024-10-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('operator', 'Operator'), ('operand', 'Operand')], max_length=10)),
                ('operator', models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR'), ('>', 'Greater Than'), ('<', 'Less Than'), ('=', 'Equals'), ('>=', 'Greater Than or Equal'), ('<=', 'Less Than or Equal')], max_length=5, null=True)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_child', to='rulevalidate.node')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_child', to='rulevalidate.node')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='rulevalidate.node')),
            ],
        ),
    ]
